In [2]:
""" INTRODUCTION TUTORIAL FOR NUMPY """
import numpy as np

In [4]:
print np.array([(1,2,3),(4,5,6)])

[[1 2 3]
 [4 5 6]]


In [9]:
print np.empty(5)
print np.ones((3,3), dtype=np.int_)

[  0.00000000e+000   0.00000000e+000   2.47032823e-323   0.00000000e+000
   2.12354999e-314]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
""" Generating random numbers"""
print np.random.randint(0,10,(3,3))

[[3 3 9]
 [7 6 5]
 [8 7 2]]


In [28]:
a = np.random.randint(0,100,(5,4))

print "# of rows:", a.shape[0]
print "# of cols:", a.shape[1]
print a.dtype

# of rows: 5
# of cols: 4
int64


In [40]:
""" Operations on ndarrays """
np.random.seed(693)
a = np.random.randint(0,10,size=(5,4))

print "Array:\n", a                             # print array
print "Array sum:", a.sum()                     # print sum of the array
print "Sum of each column:\n", a.sum(axis=0)    # print vector of sums over columns
print "Sum of each row:\n", a.sum(axis=1)       # print vector of sums over rows

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Array sum: 79
Sum of each column:
[25 15 25 14]
Sum of each row:
[ 8 12 21 24 14]


In [44]:
""" Record time of function execution """
import time

t1 = time.time()
print "Hello World"
t2 = time.time()
print "It took" ,t2-t1,"s to print statement"

Hello World
It took 0.000149965286255 s to print statement


In [47]:
""" Indexing and stuff """
a = np.random.rand(5)
indeces =np.array([3,2,1])

print a
print a[indeces]

[ 0.31127579  0.62872047  0.07569968  0.54876981  0.53860522]
[ 0.54876981  0.07569968  0.62872047]


In [51]:
""" Masking with booleans"""
a = np.random.randint(0,20,(5,4))
print a

print a.mean()
print a[a>a.mean()]

[[14 15  4 12]
 [ 9 17 17 11]
 [16  0  3  2]
 [ 1  9  2 15]
 [ 7  2 19  3]]
8.9
[14 15 12  9 17 17 11 16  9 15 19]


In [ ]:
""" Arithmetical operations"""
print "Array a:\n", a
print "Division by 2:\n", a/2.0