In [58]:
""" INTRODUCTION TUTORIAL FOR NUMPY """
import numpy as np

In [59]:
print np.array([(1,2,3),(4,5,6)])

[[1 2 3]
 [4 5 6]]


In [60]:
print np.empty(5)
print np.ones((3,3), dtype=np.int_)

[  2.47032823e-323   3.95252517e-323   4.44659081e-323   3.45845952e-322
   1.18575755e-322]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
""" Generating random numbers"""
print np.random.randint(0,10,(3,3))

[[3 5 0]
 [7 6 7]
 [3 7 2]]


In [62]:
a = np.random.randint(0,100,(5,4))

print "# of rows:", a.shape[0]
print "# of cols:", a.shape[1]
print a.dtype

# of rows: 5
# of cols: 4
int64


In [63]:
""" Operations on ndarrays """
np.random.seed(693)
a = np.random.randint(0,10,size=(5,4))

print "Array:\n", a                             # print array
print "Array sum:", a.sum()                     # print sum of the array
print "Sum of each column:\n", a.sum(axis=0)    # print vector of sums over columns
print "Sum of each row:\n", a.sum(axis=1)       # print vector of sums over rows

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Array sum: 79
Sum of each column:
[25 15 25 14]
Sum of each row:
[ 8 12 21 24 14]


In [64]:
""" Record time of function execution """
import time

t1 = time.time()
print "Hello World"
t2 = time.time()
print "It took" ,t2-t1,"s to print statement"

Hello World
It took 0.000113010406494 s to print statement


In [65]:
""" Indexing and stuff """
a = np.random.rand(5)
indeces =np.array([3,2,1])

print a
print a[indeces]

[ 0.31127579  0.62872047  0.07569968  0.54876981  0.53860522]
[ 0.54876981  0.07569968  0.62872047]


In [66]:
""" Masking with booleans"""
a = np.random.randint(0,20,(5,4))
print a

print a.mean()
print a[a>a.mean()]

[[19  1 19  5]
 [15  7 13  5]
 [ 1 15  5  6]
 [10  8  2 10]
 [ 6  7  6 19]]
8.95
[19 19 15 13 15 10 10 19]


In [67]:
""" Arithmetical operations"""
a = np.array([(1,2,3),(6,7,8)])
b = np.array([(5,4,3),(0,10,3)])
print "Array a:\n", a
print "\nArray b:\n", b
# print "\nDivision array a by 2:\n", a/2.0
print "\nAddition a + b\n",a+b 
print "\nMultiply a * b\n", a*b

Array a:
[[1 2 3]
 [6 7 8]]

Array b:
[[ 5  4  3]
 [ 0 10  3]]

Addition a + b
[[ 6  6  6]
 [ 6 17 11]]

Multiply a * b
[[ 5  8  9]
 [ 0 70 24]]
